//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PupitreEPSI_DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Ecole
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Ecole()
        {
            this.Classes = new HashSet<Classe>();
        }
    
        public int id { get; set; }
        public string intitulé { get; set; }
        public int nbClasses { get; set; }
        public int campus { get; set; }
    
        public virtual Campu Campu { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Classe> Classes { get; set; }
    }
}
