//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PupitreEPSI_DAL
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class Workshop4Entities : DbContext
    {
        public Workshop4Entities()
            : base("name=Workshop4Entities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Batiment> Batiments { get; set; }
        public virtual DbSet<Campu> Campus { get; set; }
        public virtual DbSet<Classe> Classes { get; set; }
        public virtual DbSet<Cour> Cours { get; set; }
        public virtual DbSet<Ecole> Ecoles { get; set; }
        public virtual DbSet<Equipement> Equipements { get; set; }
        public virtual DbSet<Salle> Salles { get; set; }
        public virtual DbSet<Salle_Equipement> Salle_Equipement { get; set; }
    }
}
